name: Deploy app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Set Runner Tracking ID
        run: echo "RUNNER_TRACKING_ID=${{ github.job }}" >> $GITHUB_ENV
      - run: |
          npm i
          cd frontend
          npm i
          npm run build
          pm2 start npm --name "front-end" -- run dev
          cd ..
          pm2 start npm --name "back-end" -- run start
          pm2 save
