name: Deploy app

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    outputs:
      # Use the job ID as the tracking ID
      runner_tracking_id: ${{ github.job }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm i
          cd frontend
          npm i
          npm run build
          pm2 start npm --name "front-end" -- run dev
          cd ..

    # Use the outputs in the post job cleanup
    post-job-cleanup: ${{ needs.build.outputs.runner_tracking_id }}
